name: Deploy V3 Site

on:
  push:
    branches: [dev]
    paths:
      - 'docs/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          ref: 'dev'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: packages/vant

      - name: Build Site
        run: npm run build:site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: packages/vant/site
          target-folder: v3
