name: Deploy V3 Site

on:
  push:
    branches: [dev]
    paths:
      - 'packages/vant/docs/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          ref: 'dev'
        uses: actions/setup-node@v2
          with:
            node-version: '14'
            cache: 'pnpm'

      - name: Install dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
          run_install: true

      - name: Build Site
        run: npm run build:site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: packages/vant/site-dist
          target-folder: v3
