name: Build and Deploy Site
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          yarn
          yarn release:site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4
        with:
          branch: gh-pages
          folder: site
          target-folder: v3
