name: 🔂 Surge PR Preview

on: pull_request_target

jobs:
  preview:
    runs-on: ubuntu-latest
    env:
      PUBLIC_PATH: '/'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build: |
            yarn
            ./node_modules/.bin/vant-cli build-site
          dist: site
